baseURL = "https://zweitstimme.org"
title = "zweitstimme.org"
pagination.pagerSize = 5
theme = ["PaperMod", "hugo-cite"]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

defaultContentLanguage = 'de'

[minify]
disableXML = true

[languages]

  [languages.de]
    languageName = "Deutsch"
    contentDir = "content"
    weight = 1
    title = "zweitstimme.org"

    [languages.de.params]
      [languages.de.params.homeInfoParams]

        Title = "Die wissenschaftliche Vorhersage zur Bundestagswahl"


    [languages.de.menu]

      [[languages.de.menu.main]]
      name = "Home"
      url = "/"
      weight = 5

      [[languages.de.menu.main]]
      name = "Erststimme"
      url = "erststimme"
      weight = 10

      [[languages.de.menu.main]]
      name = "Zweitstimme"
      url = "zweitstimme"
      weight = 11

      [[languages.de.menu.main]]
      name = "Team"
      url = "team"
      weight = 12

      [[languages.de.menu.main]]
      name = "Blog"
      url = "posts/blog"
      weight = 15

      [[languages.de.menu.footer]]
      name = "Datenschutz"
      url = "/datenschutz"
      weight = 10

      [[languages.de.menu.footer]]
      name = "Impressum"
      url = "/impressum"
      weight = 20

      [[languages.de.menu.footer]]
      name = "API"
      url = "/api"
      weight = 30

      [[languages.de.menu.footer]]
      name = "Twitter"
      url = "https://twitter.com/zweitstimme_org"
      weight = 40

      [[languages.de.menu.footer]]
      name = "Github"
      url = "https://github.com/zweitstimme-org"
      weight = 50

      



[outputs]
home = [
  "HTML",
  "JSON"
]

[params]
hugoVersion = "0.135.0"  # Document the Hugo version required for this site
env = "production"
description = "zweitstimme.org: Die wissenschaftliche Vorhersage zur Bundestagswahl"
author = "zweitstimme.org"
disableThemeToggle = true
defaultTheme = "light"
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false
images = [
  "papermod-cover.png"
]
mainSections = ["posts/blog"]
label.icon = "/images/logo_orange.png"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/zweitstimme_org"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/zweitstimme-org"


  [params.assets]
  favicon16x16 = "/images/favicon-16x16.png"
  favicon32x32 = "/images/favicon-32x32.png"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
    unsafe = true


[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true