baseURL = "https://zweitstimme.org"
title = "zweitstimme.org"
paginate = 5.0
theme = ["PaperMod", "hugo-cite"]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

defaultContentLanguage = 'de'

[minify]
disableXML = true

[languages]

  [languages.en]
  languageName = "English"
  contentDir = "content/en"
  weight = 2.0

    [languages.en.menu]

      [[languages.en.menu.main]]
      name = "2017"
      url = "http://2017.zweitstimme.org/index_en.html"
      weight = 5.0

      [[languages.en.menu.main]]
      name = "Team"
      url = "posts/team"
      weight = 10.0


  [languages.de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 1.0
  title = "zweitstimme.org"


    [languages.de.menu]

      [[languages.de.menu.main]]
      name = "2017"
      url = "http://2017.zweitstimme.org/index.html"
      weight = 5.0

      [[languages.de.menu.main]]
      name = "Team"
      url = "posts/team"
      weight = 10.0


[outputs]
home = [
  "HTML",
  "JSON"
]

[params]
env = "production"
description = "zweitstimme.org: Die wissenschaftliche Vorhersage zur Bundestagswahl 2021."
author = "zweitstimme.org"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false
images = [
  "papermod-cover.png"
]

  [languages.de.homeInfoParams]
  Title = "Die wissenschaftliche Vorhersage zur Bundestagswahl 2021"
  Content = "Wir sind ein [Team](posts/team) von Wahlforscher:innen der Universität Mannheim, der LMU München, der Hertie School Berlin und der HU Berlin.\n- Unser Ziel ist es, einem breiten Publikum mithilfe unseres statistischen Modells Informationen und Prognosen zur Bundestagswahl an die Hand zu geben, die über die Momentaufnahmen der politischen Stimmung durch Meinungsumfragen (bspw. „Sonntagsfragen“) hinausgehen.\n- Vorhersagen von zukünftigen Ereignissen, in diesem Fall dem Ausgang der Bundestagswahl, sind immer mit Unsicherheit behaftet. Daher ist es uns besonders wichtig, die Unsicherheit von Vorhersagemodellen wie dem von zweitstimme.org eindeutig und gut verständlich zu kommunizieren.\n- Diese Informationen können Journalist:innen, Expert:innen und Bürger:innen helfen, die tatsächliche Parteienunterstützung besser einzuschätzen, zu kommunizieren und letztlich besser informierte Wahlentscheidungen zu treffen.\n- Für die Bundestagswahl 2021 kooperieren wir mit der [Süddeutschen Zeitung](https://www.sueddeutsche.de/politik/bundestagswahl-prognose-vorhersage-1.5385101), auf deren Homepage regelmäßig [aktuelle Prognosen](https://gfx.sueddeutsche.de/apps/e342301/www/index.html) von zweitstimme.org veröffentlicht werden.\n- Unser Modell verknüpft historische Informationen zu Bundestagswahlen mit aktuellen Umfragedaten, die auf [wahlrecht.de](http://wahlrecht.de) veröffentlicht werden. Zweitstimme.org hat bereits wissenschaftlich fundierte [Prognosen zur Bundestagswahl 2017](http://2017.zweitstimme.org/index.html) geliefert und begleitet nun auch die Kampagne zur Bundestagswahl 2021.\n"

[languages.en.homeInfoParams]
  Title = "The scientific forecast of the Bundestagswahl 2021"
  Content = "We are a [team](posts/team) of political scientists from the University of Mannheim, LMU Munich, Hertie School Berlin and HU Berlin.\n- Our goal is to use our statistical model to provide a broad audience with information and forecasts about the federal election that go beyond the snapshots of political sentiment provided by opinion polls (e.g., “Sunday polls“).\n- Predictions of future events, in this case the outcome of the federal election, are always fraught with uncertainty. Therefore, it is particularly important to us to communicate the uncertainty of prediction models such as that of zweitstimme.org clearly and in a way that is easy to understand.\n- This information can help journalists, experts and citizens to better assess and communicate actual party support and ultimately make better-informed voting decisions.\n- For the 2021 Bundestag election, we are cooperating with the [Süddeutsche Zeitung](https://www.sueddeutsche.de/politik/bundestagswahl-prognose-vorhersage-1.5385101), on whose homepage [current forecasts](https://gfx.sueddeutsche.de/apps/e342301/www/index.html) are regularly published by zweitstimme.org.\n- Our model links historical information on federal elections with current polling data published on [wahlrecht.de](http://wahlrecht.de). Zweitstimme.org has already provided scientifically based forecasts for the [2017 Bundestag election](http://2017.zweitstimme.org/index_en.html) and is now also accompanying the campaign for the 2021 Bundestag election.\n"


  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/zweitstimme_org"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/zweitstimme-org"




[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
    unsafe = true


[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true